In [0]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==0.4.1
# !pip install torchvision==0.2.1
# !pip install numpy==1.14.6
# !pip install matplotlib==2.1.2
# !pip install pillow==5.0.0
# !pip install opencv-python==3.4.3.18

In [0]:
import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision.transforms as transforms
%matplotlib inline
from matplotlib import pyplot as plt

# Tensor


## Tensorの変換

In [3]:
# 1次元Tensor（ベクトル）を作成
# リストを渡す
torch_array = torch.tensor([0, 1, 2, 3])
torch_array

tensor([0, 1, 2, 3])

In [5]:
# numpy.ndarrayを作成
np_array = np.array([0, 1, 2, 3])
np_array

array([0, 1, 2, 3])

In [6]:
print(type(torch_array))
print(type(np_array))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [7]:
# numpyからの変換
torch_array = torch.from_numpy(np_array)
torch_array

tensor([0, 1, 2, 3])

In [8]:
# torchからnumpy
torch2np_array = torch_array.numpy()
torch2np_array

array([0, 1, 2, 3])

In [9]:
# 2次元Tensorを作成
np_array = np.array([[0, 1, 2], [3, 4, 5]])
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[0, 1, 2],
        [3, 4, 5]])

In [10]:
# 3次元Tensorの作成
np_array = np.array([[[1], [2]], [[3], [4]]])
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[[1],
         [2]],

        [[3],
         [4]]])

## 色々なTensorの作成

In [11]:
np_array = np.arange(10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# torch.arangeの例
torch_array = torch.arange(10)
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# np.linspaceの例
np_array = np.linspace(0, 1, 6)
np_array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
torch_array = torch.linspace(0, 1, 6)
torch_array

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

In [15]:
np_array = np.ones((3, 3))
np_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
torch_array = torch.ones((3, 3))
torch_array

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
np_array = np.zeros((2, 2))
np_array

array([[0., 0.],
       [0., 0.]])

In [18]:
torch_array = torch.zeros((2, 2))
torch_array

tensor([[0., 0.],
        [0., 0.]])

In [19]:
np_array = np.random.randn(4)
np_array

array([ 1.93737916,  1.70174875,  0.34658009, -0.12133353])

In [20]:
torch_array = torch.randn(4)
torch_array

tensor([-0.0234, -0.8817,  0.3087, -1.4556])

## Tensorの操作

In [21]:
#形状変換
torch_array = torch.arange(10)
print(torch_array)
torch_array = torch_array.view(5, 2)
print(torch_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
#軸入れ替え
torch_array = torch.arange(10)
torch_array = torch_array.view(5, 2)
print(torch_array)
torch_array = torch_array.transpose(0, 1)
print(torch_array)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [0]:
#インデックス指定
torch_array = torch.arange(10)
torch_array[2]

tensor(2)

In [0]:
#スライス
torch_array = torch.arange(10)
torch_array[2:5]

tensor([2, 3, 4])

In [0]:
#要素単位の加算
x1 = torch.arange(4)
print(torch.add(x1, 4))

#要素単位の乗算
x1 = torch.arange(4)
print(torch.mul(x1, 4))

tensor([4, 5, 6, 7])
tensor([ 0,  4,  8, 12])


In [0]:
#ベクトル同士の内積
x1 = torch.arange(4)
x2 = torch.arange(4)
print(torch.matmul(x1, x2))
print(torch.dot(x1, x2))

#行列とベクトルの積
X1 = torch.arange(8).view(2, 4)
x2 = torch.arange(4)
print(torch.matmul(X1, x2))
print(torch.mv(X1, x2))

#行列同士の積
X1 = torch.arange(8).view(2, 4)
X2 = torch.arange(8).view(2, 4).t()
print(torch.matmul(X1, X2))
print(torch.mm(X1, X2))

tensor(14)
tensor(14)
tensor([14, 38])
tensor([14, 38])
tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])


In [0]:
#バッチサイズ3の(2,4)行列と(4,2)行列の行列積 
X1 = torch.arange(24).view(-1, 2, 4)
X2 = torch.arange(24).view(-1, 4, 2)
print(X1.size())
print(X2.size())
print(torch.matmul(X1, X2))
print(torch.bmm(X1, X2))

torch.Size([3, 2, 4])
torch.Size([3, 4, 2])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])


## データ型

In [0]:
np_array = np.array([1, 2, 3])
np_array.dtype

dtype('int64')

In [0]:
np_array = np.array([1., 2., 3.])
np_array.dtype

dtype('float64')

In [0]:
np_array = np.array([0, 1, 2, 3])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.LongTensor'

In [0]:
np_array = np.array([1., 2., 3.])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.DoubleTensor'

In [0]:
np_array = np.array([1, 2, 3], dtype=float)
np_array.dtype

dtype('float64')

In [0]:
np_array = np.array([1, 2, 3], dtype=float)
torch_array = torch.from_numpy(np_array)
print(torch_array.dtype)
print(torch_array.type())

torch.float64
torch.DoubleTensor


In [0]:
np_array = np.array([1, 2, 3], dtype='int64')
torch_array = torch.from_numpy(np_array)
print(torch_array.dtype)
print(torch_array.type())

torch.int64
torch.LongTensor


In [0]:
#dtypeは型そのものを返す
type(torch_array.dtype)

torch.dtype

In [0]:
#type()は文字列が返ってくる
type(torch_array.type())

str

## Tensor形状をチェックする

In [0]:
xf_numpy = np.ndarray([2, 3], dtype='float32')
print(xf_numpy)
print(xf_numpy.shape)

[[0.    1.875 0.   ]
 [2.    0.    2.125]]
(2, 3)


In [0]:
import torch
xf_torch = torch.FloatTensor(2, 3)
print(xf_torch)
print(xf_torch.size())

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000,    nan, 0.0000]])
torch.Size([2, 3])
